export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';

export const LOAD_ORGS_SUCCESS = 'LOAD_ORGS_SUCCESS';
export const LOAD_MEMBERS_SUCCESS = 'LOAD_MEMBERS_SUCCESS';
export const CREATE_ORG_SUCCESS = 'CREATE_ORG_SUCCESS';
export const UPDATE_ORG_SUCCESS = 'UPDATE_ORG_SUCCESS';